- codefresh.yml
We are using different registry integration name to push images.
> Fix release repostiory integration name.

- .goreleaser.yml
`ldflags` for go compiler were not set with the correct path.
Tested locally with `goreleaser release --snapshot --clean`.
> fix: Correct Goreleaser ldflags

- .github/workflows/release.yml
`LDFLAGS` is the right argument name to pass to Docker build.
> Fix release.yml Docker build-args

- Makefile
Currently `make build` does not work because:
- `LDFLAGS` are not quoted
- we're not pointing at the entrypoint directory (`main.go`)
Added `make docker` to build local Docker image.
> fix: Fix Makefile target

- .github/workflows/release.yml
`LDFLAGS` Docker argument should not be quoted since this causes:
```
invalid value "'-s -w -X github.com/nobl9/sloctl/internal.BuildVersion=v0.0.98'" for flag -ldflags: parameter may not start with quote character '
```
> fix: Unquote ldflags in Release workflow

- .github/scripts/release-notes.sh
Explained in https://github.com/nobl9/nobl9-go/pull/264.
> chore: Interpret git log grep pattern as literal string

- .github/release-drafter.yml
Dependencies section, separate from Maintenance section is not really needed.
> chore: Remove dependencies section from Release Drafter

- scripts/check-generate.sh
Checking generated files should not be limited to `_enum.go` files only.
> chore: Correct check-generate

- internal/get.go
- test/get.bats
- test/inputs/get/projects.yaml
- test/test_helper/load.bash
Our backend only interprets the first query parameter value it receives.
Since we've been setting `url.Values` labels query parameter key to a list of parsed values, this caused our backend to only interpret the first value.
With example Projects:
```yaml
- apiVersion: n9/v1alpha
kind: Project
metadata:
displayName: azure-agent
labels:
env:
- dev
- dev-demo-1
team:
- bees
name: azure-agent
spec:
description: azure-agent
- apiVersion: n9/v1alpha
kind: Project
metadata:
labels:
team:
- bees
name: project-two
spec:
description: ""
```
When running:
```sh
sloctl get project -l env=dev,team=bees
sloctl get project -l team=bees,env=dev
```
We got:
- for the first command, both Projects
- for the second one, only one Project, `azure-agent`
**What should've happened?**
Both commands should only …
> fix: Correct multiple labels filtering for get commadn

- .github/pull_request_template.md
- .github/release-drafter.yml
- .github/scripts/release-notes.sh
- .markdownlint.yaml
- Makefile
- docs/DEVELOPMENT.md
- docs/RELEASE.md
> doc: Update dev docs for development and releases

- .github/workflows/e2e-tests.yml
- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
Use GH environments and a no-op step along with `needs` chaining to achieve a flow where both QA and management have to approve the release.
I also parametrized e2e tests, we might want to trigger these tests from other places too.
I also fixed the issue with Goreleaser, ref: https://github.com/nobl9/terraform-provider-nobl9/pull/182
> chore: Introduce SOC-2 compliant release process

- .github/workflows/e2e-tests-dispatch.yml
- go.mod
- go.sum
- internal/root.go
With the change in SDK behaviour in favour of optional JSON numbers handling we need to turn the flag on in order to retain correct JSON numbers handling.
https://github.com/nobl9/nobl9-go/pull/350
> chore: Use JSON numbers with updated SDK

- go.mod
- test/get.bats
- test/inputs/get/alertpolicies.yaml
- test/inputs/get/projects.yaml
- test/inputs/get/services.yaml
- test/inputs/get/slos.yaml
- test/outputs/get/alertpolicy.yaml
This PR introduces a mechanism for users to define annotations on SLOs, Services, Projects, and Alert Policies (the same objects to which we can assign labels).
Similarly to Kubernetes, users can use either labels or annotations to attach metadata to objects.
Annotations, similarly to k8s annotations, are defined as key/value maps:
```json
"metadata": {
"annotations": {
"key1" : "value1",
"key2" : "value2"
}
}
```
Added the ability to define metadata annotations on `SLOs`, `Services`, `Projects`, and `Alert Policies`.
Similarly to Kubernetes, users can now use either labels or annotations to attach metadata to objects.
> feat: PC-12282 Introduce metadata annotations

- test/docker/Dockerfile.e2e
- test/docker/Dockerfile.unit
Until https://github.com/kislyuk/yq/issues/187 is resolved, yq has to be pinned to a previous version.
> chore: Pin yq version for tests

- .goreleaser.yml
Goreleaser is currently marking release candidate releases as `latest`, this is an unwanted behaviour.
In order to prevent the tool from doing that we need to set `make_latest` to false.
Ref: https://goreleaser.com/customization/release/?h=#github
> chore: Fix goreleaser marking pre-releases as latest

- .goreleaser.yml
Correct `release.make_latest` field value to proper boolean: `false`.
> chore: Fix typo in .goreleaser.yml

- test/aws-iam-ids.bats
- test/get.bats
- test/inputs/aws-iam-ids/direct.yaml
- test/inputs/get/alertsilences.yaml
- test/inputs/get/annotations.yaml
- test/inputs/get/budgetadjustments.yaml
- test/inputs/get/directs.yaml
- test/inputs/get/slos.yaml
- test/outputs/get/direct.yaml
The Splunk Observability integration is not actively supported. End to end tests using it may me flaky. 
Change Splunk Observability direct used in e2e tests to Splunk.
- run e2e test
> chore: use supported direct type for e2e tests [PC-12979]

- Dockerfile
- cspell.yaml
Currently, we're missing certificates in our Docker image, so it won't work.
```
Post "https://accounts.nobl9.com/oauth2/auseg9kiegWKEtJZC416/v1/token": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
Switch to [distroless](https://github.com/GoogleContainerTools/distroless) image which has certificates baked in.
Similar problem I've encountered recently in another project: https://github.com/nieomylnieja/go-libyear/commit/c7faae7e234a56cb07c5a46571168e10a7d5f9a6
```shell
make docker
docker run -e SLOCTL_CLIENT_ID=$CLIENT_ID -e SLOCTL_CLIENT_SECRET=$CLIENT_SECRET sloctl get slos
```
Fixed missing TLS certificates from Docker image.
> fix: Switch to distroless image in Dockerfile [PC-13119]

- .goreleaser.yml
`brews.folder` is deprecated as per https://goreleaser.com/deprecations/#__tabbed_4_1.
Changed `brews.folder` to `brews.directory`.
> chore: change folder to directory in brews Goreleaser config

- test/apply-and-delete.bats
- test/test_helper/load.bash
With the introduction of new server-side computed fields for v1alpha Project.Spec: `createdAt` and `createdBy` the tests started failing as the helper function `_assert_objects_existence` was comparing almost the whole object.
This is too much for a simple assertion that checks if the object was actually applied, so I added additional filter to re-map the objects, extracting the basic minimum for comparison.
Ref: https://github.com/nobl9/sloctl/actions/runs/9466510383/job/26078347437
- https://github.com/nobl9/nobl9-go/pull/422
Run `make test/e2e`, remember about supplying the right env vars OR run https://github.com/nobl9/sloctl/actions/workflows/e2e-tests-dispatch.yml with this branch as target.
> chore: Adjust e2e tests for createdAt and createdBy new v1alpha Project.Spec fields

- test/dockertest/docker_test.go
We're using `github.ref_name` which is the literal tag name, when passed as the image tag it results in:
```
Unable to find image 'nobl9/sloctl:v0.3.2' locally
```
We need to trim this `v` prefix in order for it to work.
Since there's no easy way to do that in the workflow itself (because we're using reusable workflow), we need to trim it in the test code.
> chore: Trim prefix from Docker image in Docker tests

- .golangci.yml
- go.mod
- go.sum
- internal/printer/printer.go
- internal/replay.go
The `replace` clause in `go.mod` was causing `go install` to fail with:
```
go install [github.com/nobl9/sloctl/cmd/sloctl@latest](http://github.com/nobl9/sloctl/cmd/sloctl@latest)
go: downloading [github.com/nobl9/sloctl](http://github.com/nobl9/sloctl) v0.3.2
go: [github.com/nobl9/sloctl/cmd/sloctl@latest](http://github.com/nobl9/sloctl/cmd/sloctl@latest) (in [github.com/nobl9/sloctl@v0.3.2](http://github.com/nobl9/sloctl@v0.3.2)):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
```
- https://github.com/nobl9/nobl9-go/pull/482
Fixed `go install` malfunction introduced in `v0.3.2` caused by `replace` clause in `go.mod`.
> fix: Remove replace clause

- test/dockertest/docker_test.go
We need to replace the string instead of trimming prefix as we receive the whole image not just the tag.
```shell
SLOCTL_E2E_DOCKER_TEST_IMAGE=nobl9/sloctl:v0.3.3 make test/go/e2e-docker
```
> chore: Correct string replacement in Docker e2e tests

- Dockerfile
Resolves the issue https://nvd.nist.gov/vuln/detail/CVE-2024-24790
The docker image has been updated to resolve critical level vuln in stdlib (https://nvd.nist.gov/vuln/detail/CVE-2024-24790)
> chore: Update docker image to 1.22-alpine3.20

- test/apply-and-delete.bats
- test/aws-iam-ids.bats
- test/delete-by-name.bats
- test/get.bats
- test/test_helper/load.bash
Since we introduced `run --separate-stderr` flag some time ago in order to avoid `assert_output` checking both stdout and stderr (which can contain stuff like "retrying" notices) and failing due to that, it had a side effect on `assert_success`, which now only prints `$output` which is only stdout (stderr is separated into `$stderr`).
To fix that we need to give `assert_success` conjoined stdout and stderr.
> fix: Add missing stderr from assert_success output

- .github/workflows/e2e-tests-dispatch.yml
- internal/apply.go
- internal/aws_iam_ids.go
- internal/config.go
- internal/delete.go
- internal/flags.go
- internal/get.go
- internal/replay.go
- internal/root.go
- test/delete-by-name.bats
- test/get.bats
- test/test_helper/load.bash
For a long time `sloctl` had `-p` and `-A` flags available in the global scope, even if specific sub-commands were not using it.
Similarly, `-l` flag for `get <object>` command was available even for objects which do not support labels filtering.
This PR finally fixes these issues and sets the aforementioned flags contextually, only when it makes sense.
- Ensure all the `-p` flag usage works for project scoped objects on `delete` (by name) and `get` commands.
- Ensure `-A` flag is only visible/usable for `get` command for project scoped objects, and that it works.
- Ensure `-l` flag for labels filtering is only visible for objects supporting labels, and that it works.
Successful run: https://github.com/nobl9/sloctl/actions/runs/10200396849/job/28219757765
`get` command exposes `-l` flag …
> feat: Improve flags handling [PC-13534]

- .github/workflows/release-candidate.yml
- .github/workflows/release.yml
- .goreleaser.yml
Followed this tutorial to make sure the upgrade is successful: https://goreleaser.com/blog/goreleaser-v2
> chore: Update goreleaser to v2 and action to v6

- internal/flags.go
- internal/get.go
Alerts, while not directly Project scoped, support Project filtering.
With the changes introduced in https://github.com/nobl9/sloctl/pull/177, the flag was removed.
This PR brings it back.
Build sloctl with `make build` locally and run `sloctl get alert -A` and `sloctl get alert -p <project_name>`.
`sloctl get alert` once again supports both `-p` and `-A` flags for Project filtering.
These flags were removed as a regression in v0.4.0.
> fix: Bring back get alerts project flags

- internal/apply.go
- internal/delete.go
- internal/flags.go
- internal/get.go
- internal/replay.go
https://github.com/nobl9/sloctl/pull/177 removed default project flags, unfortunately we missed the `sloctl replay` command which also relied on them.
This PR brings the `-p` flag back for `sloctl replay` command.
> fix: Add project flag back again for sloctl replay

- internal/replay_example.sh
- internal/root.go
Correct invalid docs for `sloctl replay`.
Make `help` flag override persistent.
`sloctl replay` help message examples were presenting unsupported usage of stdin for passing file config.
The only supported way of providing the config is with `-f` flag.
> fix: Correct sloctl replay help

- test/inputs/delete-by-name/report.yaml
Correct failing delete report test (new required `thresholds` field was missing).
> fix: Fix delete report test

- Makefile
- cspell.yaml
By default `go fmt` calls `gofmt -w -l`, with the recent golangci linter changes it seems it's not enough, and rightfully so.
It now requires the files to be formatted with `-s` flag which simplifies code, for instance removing unnecessary type literals in slice declarations. 
Example linter fail due to unsimplified code: https://github.com/nobl9/nobl9-go/actions/runs/11123928510/job/30908411560
> chore: Update gofmt usage

- internal/replay.go
- internal/replay_list.go
- package.json
Ability to list all queued replays through sloctl.
Added new command `sloctl replay list`
https://github.com/nobl9/n9/pull/15630
> feat: List the queued replays [PC-13341]

- internal/replay_delete.go
Wrong formatting of string causing artifacts at the end.
> fix: Fix string display

- internal/replay.go
Adjusting the messaging for the `replay` command, including navigating to the proper docs location about the replay feature. 
Only messages for `replay` command were changed.
Try to queue the replay using `sloctl` and observe changed messaging for a long description of `replay` command.
Introducing Replay queues - the ability to queue the replay to be invoked automatically.
> chore: Update messaging around `replay` command [PC-14729]

- .goreleaser.yml
- README.md
- cspell.yaml
- install.bash
- test/docker/Dockerfile.unit
- test/install-script.bats
- test/setup_suite.bash
Currently we're only building binaries for amd64 architecture, it would be good to support arm64 as well.
In addition, many tools often provide an install script which automates the process of installing/upgrading these tools.
Run install script:
```bash
./install.bash -v v0.11.0-rc1 -d <YOUR_PATH>
```
You can also test the commands for installment from README, for instance:
```bash
curl -fsSL -o install.bash https://raw.githubusercontent.com/nobl9/sloctl/extend-release-targets-and-add-install-script/install.bash
```
Sloctl pre-built binaries are now also built for arm64 architecture.
In addition there's now a now method of installing sloctl, via an install script.
For more details refer to the [README](https://github.com/nobl9/sloctl/tree/main?tab=readme-ov-file#script).
Sloctl released …
> feat: Extend release targets and add install.bash script

- .goreleaser.yml
Changes introduced in https://github.com/nobl9/sloctl/pull/288 broke this glob pattern:
```ruby
bin.install Dir['sloctl-*-0.11.0'].first()  => "sloctl"
```
Since this is not a regular expression but a glob pattern, the newly added arch suffix (and the moved OS name) failed to match.
> fix: Update Homebrew formula

- test/docker/Dockerfile.e2e
To reduce token requests we decided to enable use the same config between tests.
> chore: Enable token caching for e2e tests

- internal/flags.go
- internal/get.go
- test/adjustments-e2e.bats
Changes introduced in https://github.com/nobl9/sloctl/pull/361 have broken how `sloctl get agent` is printing "no resources message", i.e. it's not printing anything now.
This PR fixes the issue, in addition `sloctl get budgetadjustment`, when finding no resource will print `No resources found.` instead of specifying the project. The command in its bare form is not project aware and should not have been printing such message indicating so, while it has `-p` filter, it can only be used in conjunction with `--slo` flag.
Introduces a new helper function `registerProjectFlag` to centralize the registration of the `--project` flag. This reduces code duplication across multiple commands. The function is now used in various places where the `--project` flag was previously registered manually. …
> fix: correct object printing logic and budget adjustment flags handling

- internal/flags/timevalue.go
- internal/replay_errors.go
- test/adjustments-unit.bats
Improve error message to clarify what date formats are valid to use with this feature.
Included better examples of valid date formats.
This change only affects error messages. I have not tested it.
Included better examples of valid date formats for `sloctl budgetadjustments events get` `--from` and `--to` flags.
> fix: Update error messages for invalid date format tests
